#!/bin/sh

wget http://tools.ietf.org/rfc/rfc4614.txt


for RFC in `grep "\[RFC" rfc4614.txt | sed -e "s/^.*RFC/rfc/" | grep -v "rfc \|rfc$" | sed -e "s/\].*$//g" |sort |uniq`; do
	wget http://tools.ietf.org/rfc/$RFC.txt
done

wget http://tools.ietf.org/rfc/rfc3927.txt

# Get PPP related RFC's
for RFC in $(echo 1332 1334 1661 1662 1994 | sed -r 's/[^ ]+/rfc&/g'); do
	wget http://tools.ietf.org/rfc/${RFC}.txt
done
