/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      CMock_Init(); \
      setUp(); \
      TestFunc(); \
      CMock_Verify(); \
  } \
  CMock_Destroy(); \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include "cmock.h"
#include <setjmp.h>
#include <stdio.h>
#include "pico_vector.h"
#include <stdlib.h>
#include "Mockpico_zalloc.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_pico_vector_init(void);
extern void test_pico_vector_size(void);
extern void test_pico_vector_push_back(void);
extern void test_pico_vector_grow(void);
extern void test_pico_vector_clear(void);
extern void test_pico_vector_destroy(void);
extern void test_pico_iterator(void);


//=======Mock Management=====
static void CMock_Init(void)
{
  Mockpico_zalloc_Init();
}
static void CMock_Verify(void)
{
  Mockpico_zalloc_Verify();
}
static void CMock_Destroy(void)
{
  Mockpico_zalloc_Destroy();
}

//=======Test Reset Option=====
void resetTest()
{
  CMock_Verify();
  CMock_Destroy();
  tearDown();
  CMock_Init();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "Testpico_vector.c";
  UnityBegin();
  RUN_TEST(test_pico_vector_init, 32);
  RUN_TEST(test_pico_vector_size, 49);
  RUN_TEST(test_pico_vector_push_back, 59);
  RUN_TEST(test_pico_vector_grow, 78);
  RUN_TEST(test_pico_vector_clear, 106);
  RUN_TEST(test_pico_vector_destroy, 122);
  RUN_TEST(test_pico_iterator, 144);

  return (UnityEnd());
}
