/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      CMock_Init(); \
      setUp(); \
      TestFunc(); \
      CMock_Verify(); \
  } \
  CMock_Destroy(); \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include "cmock.h"
#include <setjmp.h>
#include <stdio.h>
#include "zmq_tests.h"
#include "pico_ipv4.h"
#include "pico_socket.h"
#include "Mockpico_zmtp.h"
#include "Mockpico_ipv4.h"
#include "Mockpico_vector.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_zmq_socket_req(void);
extern void test_zmq_socket_rep(void);
extern void test_zmq_socket_pub(void);
extern void test_zmq_connect(void);
extern void test_zmq_req(void);


//=======Mock Management=====
static void CMock_Init(void)
{
  Mockpico_zmtp_Init();
  Mockpico_ipv4_Init();
  Mockpico_vector_Init();
}
static void CMock_Verify(void)
{
  Mockpico_zmtp_Verify();
  Mockpico_ipv4_Verify();
  Mockpico_vector_Verify();
}
static void CMock_Destroy(void)
{
  Mockpico_zmtp_Destroy();
  Mockpico_ipv4_Destroy();
  Mockpico_vector_Destroy();
}

//=======Test Reset Option=====
void resetTest()
{
  CMock_Verify();
  CMock_Destroy();
  tearDown();
  CMock_Init();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "Testzmq_tests.c";
  UnityBegin();
  RUN_TEST(test_zmq_socket_req, 20);
  RUN_TEST(test_zmq_socket_rep, 38);
  RUN_TEST(test_zmq_socket_pub, 43);
  RUN_TEST(test_zmq_connect, 53);
  RUN_TEST(test_zmq_req, 69);

  return (UnityEnd());
}
