OPTIONS+=-DPICO_SUPPORT_6LOWPAN -DPICO_SUPPORT_IPV6 -DPICO_SUPPORT_802154
MOD_OBJ+=$(LIBBASE)modules/pico_6lowpan_ll.o
MOD_OBJ+=$(LIBBASE)modules/pico_6lowpan.o
MOD_OBJ+=$(LIBBASE)modules/pico_802154.o
