/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKPICO_ZALLOC_H
#define _MOCKPICO_ZALLOC_H

//#include "pico_zalloc.h"

void Mockpico_zalloc_Init(void);
void Mockpico_zalloc_Destroy(void);
void Mockpico_zalloc_Verify(void);




#define pico_zalloc_ExpectAndReturn(size, cmock_retval) pico_zalloc_CMockExpectAndReturn(__LINE__, size, cmock_retval)
void pico_zalloc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int size, void* cmock_to_return);
#define pico_free_Expect(mem) pico_free_CMockExpect(__LINE__, mem)
void pico_free_CMockExpect(UNITY_LINE_TYPE cmock_line, void* mem);

#endif
