/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockpico_zmtp.h"

typedef struct _CMOCK_zmtp_socket_open_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct zmtp_socket* ReturnVal;
  uint16_t Expected_net;
  uint16_t Expected_proto;
  uint8_t Expected_type;
  cmock_pico_zmtp_func_ptr1 Expected_wakeup;

} CMOCK_zmtp_socket_open_CALL_INSTANCE;

typedef struct _CMOCK_zmtp_socket_bind_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int8_t ReturnVal;
  struct zmtp_socket* Expected_s;
  void* Expected_local_addr;
  uint16_t* Expected_port;

} CMOCK_zmtp_socket_bind_CALL_INSTANCE;

typedef struct _CMOCK_zmtp_socket_connect_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int8_t ReturnVal;
  struct zmtp_socket* Expected_s;
  void* Expected_srv_addr;
  uint16_t Expected_remote_port;

} CMOCK_zmtp_socket_connect_CALL_INSTANCE;

typedef struct _CMOCK_zmtp_socket_send_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int8_t ReturnVal;
  struct zmtp_socket* Expected_s;
  struct zmq_msg** Expected_msg;
  uint16_t Expected_len;

} CMOCK_zmtp_socket_send_CALL_INSTANCE;

typedef struct _CMOCK_zmtp_socket_close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int8_t ReturnVal;
  struct zmtp_socket* Expected_s;

} CMOCK_zmtp_socket_close_CALL_INSTANCE;

static struct Mockpico_zmtpInstance
{
  CMOCK_zmtp_socket_open_CALLBACK zmtp_socket_open_CallbackFunctionPointer;
  int zmtp_socket_open_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE zmtp_socket_open_CallInstance;
  CMOCK_zmtp_socket_bind_CALLBACK zmtp_socket_bind_CallbackFunctionPointer;
  int zmtp_socket_bind_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE zmtp_socket_bind_CallInstance;
  CMOCK_zmtp_socket_connect_CALLBACK zmtp_socket_connect_CallbackFunctionPointer;
  int zmtp_socket_connect_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE zmtp_socket_connect_CallInstance;
  CMOCK_zmtp_socket_send_CALLBACK zmtp_socket_send_CallbackFunctionPointer;
  int zmtp_socket_send_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE zmtp_socket_send_CallInstance;
  CMOCK_zmtp_socket_close_CALLBACK zmtp_socket_close_CallbackFunctionPointer;
  int zmtp_socket_close_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE zmtp_socket_close_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockpico_zmtp_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.zmtp_socket_open_CallInstance, cmock_line, "Function 'zmtp_socket_open' called less times than expected.");
  if (Mock.zmtp_socket_open_CallbackFunctionPointer != NULL)
    Mock.zmtp_socket_open_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.zmtp_socket_bind_CallInstance, cmock_line, "Function 'zmtp_socket_bind' called less times than expected.");
  if (Mock.zmtp_socket_bind_CallbackFunctionPointer != NULL)
    Mock.zmtp_socket_bind_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.zmtp_socket_connect_CallInstance, cmock_line, "Function 'zmtp_socket_connect' called less times than expected.");
  if (Mock.zmtp_socket_connect_CallbackFunctionPointer != NULL)
    Mock.zmtp_socket_connect_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.zmtp_socket_send_CallInstance, cmock_line, "Function 'zmtp_socket_send' called less times than expected.");
  if (Mock.zmtp_socket_send_CallbackFunctionPointer != NULL)
    Mock.zmtp_socket_send_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.zmtp_socket_close_CallInstance, cmock_line, "Function 'zmtp_socket_close' called less times than expected.");
  if (Mock.zmtp_socket_close_CallbackFunctionPointer != NULL)
    Mock.zmtp_socket_close_CallInstance = CMOCK_GUTS_NONE;
}

void Mockpico_zmtp_Init(void)
{
  Mockpico_zmtp_Destroy();
}

void Mockpico_zmtp_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.zmtp_socket_open_CallbackFunctionPointer = NULL;
  Mock.zmtp_socket_open_CallbackCalls = 0;
  Mock.zmtp_socket_bind_CallbackFunctionPointer = NULL;
  Mock.zmtp_socket_bind_CallbackCalls = 0;
  Mock.zmtp_socket_connect_CallbackFunctionPointer = NULL;
  Mock.zmtp_socket_connect_CallbackCalls = 0;
  Mock.zmtp_socket_send_CallbackFunctionPointer = NULL;
  Mock.zmtp_socket_send_CallbackCalls = 0;
  Mock.zmtp_socket_close_CallbackFunctionPointer = NULL;
  Mock.zmtp_socket_close_CallbackCalls = 0;
}

struct zmtp_socket* zmtp_socket_open(uint16_t net, uint16_t proto, uint8_t type, cmock_pico_zmtp_func_ptr1 wakeup)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_zmtp_socket_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_zmtp_socket_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.zmtp_socket_open_CallInstance);
  Mock.zmtp_socket_open_CallInstance = CMock_Guts_MemNext(Mock.zmtp_socket_open_CallInstance);
  if (Mock.zmtp_socket_open_CallbackFunctionPointer != NULL)
  {
    return Mock.zmtp_socket_open_CallbackFunctionPointer(net, proto, type, wakeup, Mock.zmtp_socket_open_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'zmtp_socket_open' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_net, net, cmock_line, "Function 'zmtp_socket_open' called with unexpected value for argument 'net'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_proto, proto, cmock_line, "Function 'zmtp_socket_open' called with unexpected value for argument 'proto'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_type, type, cmock_line, "Function 'zmtp_socket_open' called with unexpected value for argument 'type'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_wakeup, wakeup, cmock_line, "Function 'zmtp_socket_open' called with unexpected value for argument 'wakeup'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_zmtp_socket_open(CMOCK_zmtp_socket_open_CALL_INSTANCE* cmock_call_instance, uint16_t net, uint16_t proto, uint8_t type, cmock_pico_zmtp_func_ptr1 wakeup)
{
  cmock_call_instance->Expected_net = net;
  cmock_call_instance->Expected_proto = proto;
  cmock_call_instance->Expected_type = type;
  memcpy(&cmock_call_instance->Expected_wakeup, &wakeup, sizeof(cmock_pico_zmtp_func_ptr1));
}

void zmtp_socket_open_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t net, uint16_t proto, uint8_t type, cmock_pico_zmtp_func_ptr1 wakeup, struct zmtp_socket* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_zmtp_socket_open_CALL_INSTANCE));
  CMOCK_zmtp_socket_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_zmtp_socket_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.zmtp_socket_open_CallInstance = CMock_Guts_MemChain(Mock.zmtp_socket_open_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_zmtp_socket_open(cmock_call_instance, net, proto, type, wakeup);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void zmtp_socket_open_StubWithCallback(CMOCK_zmtp_socket_open_CALLBACK Callback)
{
  Mock.zmtp_socket_open_CallbackFunctionPointer = Callback;
}

int8_t zmtp_socket_bind(struct zmtp_socket* s, void* local_addr, uint16_t* port)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_zmtp_socket_bind_CALL_INSTANCE* cmock_call_instance = (CMOCK_zmtp_socket_bind_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.zmtp_socket_bind_CallInstance);
  Mock.zmtp_socket_bind_CallInstance = CMock_Guts_MemNext(Mock.zmtp_socket_bind_CallInstance);
  if (Mock.zmtp_socket_bind_CallbackFunctionPointer != NULL)
  {
    return Mock.zmtp_socket_bind_CallbackFunctionPointer(s, local_addr, port, Mock.zmtp_socket_bind_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'zmtp_socket_bind' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_s), (void*)(s), sizeof(struct zmtp_socket), cmock_line, "Function 'zmtp_socket_bind' called with unexpected value for argument 's'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_local_addr, local_addr, cmock_line, "Function 'zmtp_socket_bind' called with unexpected value for argument 'local_addr'.");
  }
  {
    if (cmock_call_instance->Expected_port == NULL)
      { UNITY_TEST_ASSERT_NULL(port, cmock_line, "Expected NULL. Function 'zmtp_socket_bind' called with unexpected value for argument 'port'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_port, port, 1, cmock_line, "Function 'zmtp_socket_bind' called with unexpected value for argument 'port'."); }
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_zmtp_socket_bind(CMOCK_zmtp_socket_bind_CALL_INSTANCE* cmock_call_instance, struct zmtp_socket* s, void* local_addr, uint16_t* port)
{
  cmock_call_instance->Expected_s = s;
  cmock_call_instance->Expected_local_addr = local_addr;
  cmock_call_instance->Expected_port = port;
}

void zmtp_socket_bind_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct zmtp_socket* s, void* local_addr, uint16_t* port, int8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_zmtp_socket_bind_CALL_INSTANCE));
  CMOCK_zmtp_socket_bind_CALL_INSTANCE* cmock_call_instance = (CMOCK_zmtp_socket_bind_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.zmtp_socket_bind_CallInstance = CMock_Guts_MemChain(Mock.zmtp_socket_bind_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_zmtp_socket_bind(cmock_call_instance, s, local_addr, port);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void zmtp_socket_bind_StubWithCallback(CMOCK_zmtp_socket_bind_CALLBACK Callback)
{
  Mock.zmtp_socket_bind_CallbackFunctionPointer = Callback;
}

int8_t zmtp_socket_connect(struct zmtp_socket* s, void* srv_addr, uint16_t remote_port)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_zmtp_socket_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_zmtp_socket_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.zmtp_socket_connect_CallInstance);
  Mock.zmtp_socket_connect_CallInstance = CMock_Guts_MemNext(Mock.zmtp_socket_connect_CallInstance);
  if (Mock.zmtp_socket_connect_CallbackFunctionPointer != NULL)
  {
    return Mock.zmtp_socket_connect_CallbackFunctionPointer(s, srv_addr, remote_port, Mock.zmtp_socket_connect_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'zmtp_socket_connect' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_s), (void*)(s), sizeof(struct zmtp_socket), cmock_line, "Function 'zmtp_socket_connect' called with unexpected value for argument 's'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_srv_addr, srv_addr, cmock_line, "Function 'zmtp_socket_connect' called with unexpected value for argument 'srv_addr'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_remote_port, remote_port, cmock_line, "Function 'zmtp_socket_connect' called with unexpected value for argument 'remote_port'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_zmtp_socket_connect(CMOCK_zmtp_socket_connect_CALL_INSTANCE* cmock_call_instance, struct zmtp_socket* s, void* srv_addr, uint16_t remote_port)
{
  cmock_call_instance->Expected_s = s;
  cmock_call_instance->Expected_srv_addr = srv_addr;
  cmock_call_instance->Expected_remote_port = remote_port;
}

void zmtp_socket_connect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct zmtp_socket* s, void* srv_addr, uint16_t remote_port, int8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_zmtp_socket_connect_CALL_INSTANCE));
  CMOCK_zmtp_socket_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_zmtp_socket_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.zmtp_socket_connect_CallInstance = CMock_Guts_MemChain(Mock.zmtp_socket_connect_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_zmtp_socket_connect(cmock_call_instance, s, srv_addr, remote_port);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void zmtp_socket_connect_StubWithCallback(CMOCK_zmtp_socket_connect_CALLBACK Callback)
{
  Mock.zmtp_socket_connect_CallbackFunctionPointer = Callback;
}

int8_t zmtp_socket_send(struct zmtp_socket* s, struct zmq_msg** msg, uint16_t len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_zmtp_socket_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_zmtp_socket_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.zmtp_socket_send_CallInstance);
  Mock.zmtp_socket_send_CallInstance = CMock_Guts_MemNext(Mock.zmtp_socket_send_CallInstance);
  if (Mock.zmtp_socket_send_CallbackFunctionPointer != NULL)
  {
    return Mock.zmtp_socket_send_CallbackFunctionPointer(s, msg, len, Mock.zmtp_socket_send_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'zmtp_socket_send' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_s), (void*)(s), sizeof(struct zmtp_socket), cmock_line, "Function 'zmtp_socket_send' called with unexpected value for argument 's'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_msg, msg, cmock_line, "Function 'zmtp_socket_send' called with unexpected value for argument 'msg'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_len, len, cmock_line, "Function 'zmtp_socket_send' called with unexpected value for argument 'len'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_zmtp_socket_send(CMOCK_zmtp_socket_send_CALL_INSTANCE* cmock_call_instance, struct zmtp_socket* s, struct zmq_msg** msg, uint16_t len)
{
  cmock_call_instance->Expected_s = s;
  cmock_call_instance->Expected_msg = msg;
  cmock_call_instance->Expected_len = len;
}

void zmtp_socket_send_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct zmtp_socket* s, struct zmq_msg** msg, uint16_t len, int8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_zmtp_socket_send_CALL_INSTANCE));
  CMOCK_zmtp_socket_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_zmtp_socket_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.zmtp_socket_send_CallInstance = CMock_Guts_MemChain(Mock.zmtp_socket_send_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_zmtp_socket_send(cmock_call_instance, s, msg, len);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void zmtp_socket_send_StubWithCallback(CMOCK_zmtp_socket_send_CALLBACK Callback)
{
  Mock.zmtp_socket_send_CallbackFunctionPointer = Callback;
}

int8_t zmtp_socket_close(struct zmtp_socket* s)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_zmtp_socket_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_zmtp_socket_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.zmtp_socket_close_CallInstance);
  Mock.zmtp_socket_close_CallInstance = CMock_Guts_MemNext(Mock.zmtp_socket_close_CallInstance);
  if (Mock.zmtp_socket_close_CallbackFunctionPointer != NULL)
  {
    return Mock.zmtp_socket_close_CallbackFunctionPointer(s, Mock.zmtp_socket_close_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'zmtp_socket_close' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_s), (void*)(s), sizeof(struct zmtp_socket), cmock_line, "Function 'zmtp_socket_close' called with unexpected value for argument 's'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_zmtp_socket_close(CMOCK_zmtp_socket_close_CALL_INSTANCE* cmock_call_instance, struct zmtp_socket* s)
{
  cmock_call_instance->Expected_s = s;
}

void zmtp_socket_close_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct zmtp_socket* s, int8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_zmtp_socket_close_CALL_INSTANCE));
  CMOCK_zmtp_socket_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_zmtp_socket_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.zmtp_socket_close_CallInstance = CMock_Guts_MemChain(Mock.zmtp_socket_close_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_zmtp_socket_close(cmock_call_instance, s);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void zmtp_socket_close_StubWithCallback(CMOCK_zmtp_socket_close_CALLBACK Callback)
{
  Mock.zmtp_socket_close_CallbackFunctionPointer = Callback;
}

