/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockpico_zalloc.h"

typedef struct _CMOCK_pico_zalloc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* ReturnVal;
  int Expected_size;

} CMOCK_pico_zalloc_CALL_INSTANCE;

typedef struct _CMOCK_pico_free_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* Expected_mem;

} CMOCK_pico_free_CALL_INSTANCE;

static struct Mockpico_zallocInstance
{
  int pico_zalloc_IgnoreBool;
  void* pico_zalloc_FinalReturn;
  CMOCK_pico_zalloc_CALLBACK pico_zalloc_CallbackFunctionPointer;
  int pico_zalloc_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE pico_zalloc_CallInstance;
  int pico_free_IgnoreBool;
  CMOCK_pico_free_CALLBACK pico_free_CallbackFunctionPointer;
  int pico_free_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE pico_free_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockpico_zalloc_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.pico_zalloc_IgnoreBool)
    Mock.pico_zalloc_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pico_zalloc_CallInstance, cmock_line, "Function 'pico_zalloc' called less times than expected.");
  if (Mock.pico_zalloc_CallbackFunctionPointer != NULL)
    Mock.pico_zalloc_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.pico_free_IgnoreBool)
    Mock.pico_free_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pico_free_CallInstance, cmock_line, "Function 'pico_free' called less times than expected.");
  if (Mock.pico_free_CallbackFunctionPointer != NULL)
    Mock.pico_free_CallInstance = CMOCK_GUTS_NONE;
}

void Mockpico_zalloc_Init(void)
{
  Mockpico_zalloc_Destroy();
}

void Mockpico_zalloc_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.pico_zalloc_CallbackFunctionPointer = NULL;
  Mock.pico_zalloc_CallbackCalls = 0;
  Mock.pico_free_CallbackFunctionPointer = NULL;
  Mock.pico_free_CallbackCalls = 0;
}

void* pico_zalloc(int size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pico_zalloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_zalloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pico_zalloc_CallInstance);
  Mock.pico_zalloc_CallInstance = CMock_Guts_MemNext(Mock.pico_zalloc_CallInstance);
  if (Mock.pico_zalloc_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.pico_zalloc_FinalReturn;
    Mock.pico_zalloc_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.pico_zalloc_CallbackFunctionPointer != NULL)
  {
    return Mock.pico_zalloc_CallbackFunctionPointer(size, Mock.pico_zalloc_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'pico_zalloc' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_size, size, cmock_line, "Function 'pico_zalloc' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pico_zalloc(CMOCK_pico_zalloc_CALL_INSTANCE* cmock_call_instance, int size)
{
  cmock_call_instance->Expected_size = size;
}

void pico_zalloc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pico_zalloc_CALL_INSTANCE));
  CMOCK_pico_zalloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_zalloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.pico_zalloc_CallInstance = CMock_Guts_MemChain(Mock.pico_zalloc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.pico_zalloc_IgnoreBool = (int)1;
}

void pico_zalloc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int size, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pico_zalloc_CALL_INSTANCE));
  CMOCK_pico_zalloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_zalloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.pico_zalloc_CallInstance = CMock_Guts_MemChain(Mock.pico_zalloc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pico_zalloc(cmock_call_instance, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void pico_zalloc_StubWithCallback(CMOCK_pico_zalloc_CALLBACK Callback)
{
  Mock.pico_zalloc_CallbackFunctionPointer = Callback;
}

void pico_free(void* mem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pico_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pico_free_CallInstance);
  Mock.pico_free_CallInstance = CMock_Guts_MemNext(Mock.pico_free_CallInstance);
  if (Mock.pico_free_IgnoreBool)
  {
    return;
  }
  if (Mock.pico_free_CallbackFunctionPointer != NULL)
  {
    Mock.pico_free_CallbackFunctionPointer(mem, Mock.pico_free_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'pico_free' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_mem, mem, cmock_line, "Function 'pico_free' called with unexpected value for argument 'mem'.");
  }
}

void CMockExpectParameters_pico_free(CMOCK_pico_free_CALL_INSTANCE* cmock_call_instance, void* mem)
{
  cmock_call_instance->Expected_mem = mem;
}

void pico_free_CMockIgnore(void)
{
  Mock.pico_free_IgnoreBool = (int)1;
}

void pico_free_CMockExpect(UNITY_LINE_TYPE cmock_line, void* mem)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pico_free_CALL_INSTANCE));
  CMOCK_pico_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.pico_free_CallInstance = CMock_Guts_MemChain(Mock.pico_free_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pico_free(cmock_call_instance, mem);
}

void pico_free_StubWithCallback(CMOCK_pico_free_CALLBACK Callback)
{
  Mock.pico_free_CallbackFunctionPointer = Callback;
}

