/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKPICO_VECTOR_H
#define _MOCKPICO_VECTOR_H

#include "pico_vector.h"

void Mockpico_vector_Init(void);
void Mockpico_vector_Destroy(void);
void Mockpico_vector_Verify(void);




#define pico_vector_begin_ExpectAndReturn(vector, cmock_retval) pico_vector_begin_CMockExpectAndReturn(__LINE__, vector, cmock_retval)
void pico_vector_begin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct pico_vector* vector, struct pico_vector_iterator* cmock_to_return);
#define pico_vector_iterator_next_ExpectAndReturn(iterator, cmock_retval) pico_vector_iterator_next_CMockExpectAndReturn(__LINE__, iterator, cmock_retval)
void pico_vector_iterator_next_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct pico_vector_iterator* iterator, struct pico_vector_iterator* cmock_to_return);
#define pico_vector_push_back_ExpectAndReturn(vector, data, cmock_retval) pico_vector_push_back_CMockExpectAndReturn(__LINE__, vector, data, cmock_retval)
void pico_vector_push_back_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct pico_vector* vector, void* data, int cmock_to_return);
#define pico_vector_pop_back_ExpectAndReturn(vector, cmock_retval) pico_vector_pop_back_CMockExpectAndReturn(__LINE__, vector, cmock_retval)
void pico_vector_pop_back_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct pico_vector* vector, void* cmock_to_return);
#define pico_vector_clear_Expect(vector) pico_vector_clear_CMockExpect(__LINE__, vector)
void pico_vector_clear_CMockExpect(UNITY_LINE_TYPE cmock_line, struct pico_vector* vector);
#define pico_vector_destroy_Expect(vector) pico_vector_destroy_CMockExpect(__LINE__, vector)
void pico_vector_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line, struct pico_vector* vector);
#define pico_vector_allocation_strategy_times2_ExpectAndReturn(vector, cmock_retval) pico_vector_allocation_strategy_times2_CMockExpectAndReturn(__LINE__, vector, cmock_retval)
void pico_vector_allocation_strategy_times2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct pico_vector* vector, void* cmock_to_return);

#endif
