/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockpico_vector.h"

typedef struct _CMOCK_pico_vector_begin_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct pico_vector_iterator* ReturnVal;
  struct pico_vector* Expected_vector;

} CMOCK_pico_vector_begin_CALL_INSTANCE;

typedef struct _CMOCK_pico_vector_iterator_next_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct pico_vector_iterator* ReturnVal;
  struct pico_vector_iterator* Expected_iterator;

} CMOCK_pico_vector_iterator_next_CALL_INSTANCE;

typedef struct _CMOCK_pico_vector_push_back_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  struct pico_vector* Expected_vector;
  void* Expected_data;

} CMOCK_pico_vector_push_back_CALL_INSTANCE;

typedef struct _CMOCK_pico_vector_pop_back_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* ReturnVal;
  struct pico_vector* Expected_vector;

} CMOCK_pico_vector_pop_back_CALL_INSTANCE;

typedef struct _CMOCK_pico_vector_clear_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct pico_vector* Expected_vector;

} CMOCK_pico_vector_clear_CALL_INSTANCE;

typedef struct _CMOCK_pico_vector_destroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct pico_vector* Expected_vector;

} CMOCK_pico_vector_destroy_CALL_INSTANCE;

typedef struct _CMOCK_pico_vector_allocation_strategy_times2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* ReturnVal;
  struct pico_vector* Expected_vector;

} CMOCK_pico_vector_allocation_strategy_times2_CALL_INSTANCE;

static struct Mockpico_vectorInstance
{
  CMOCK_MEM_INDEX_TYPE pico_vector_begin_CallInstance;
  CMOCK_MEM_INDEX_TYPE pico_vector_iterator_next_CallInstance;
  CMOCK_MEM_INDEX_TYPE pico_vector_push_back_CallInstance;
  CMOCK_MEM_INDEX_TYPE pico_vector_pop_back_CallInstance;
  CMOCK_MEM_INDEX_TYPE pico_vector_clear_CallInstance;
  CMOCK_MEM_INDEX_TYPE pico_vector_destroy_CallInstance;
  CMOCK_MEM_INDEX_TYPE pico_vector_allocation_strategy_times2_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockpico_vector_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pico_vector_begin_CallInstance, cmock_line, "Function 'pico_vector_begin' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pico_vector_iterator_next_CallInstance, cmock_line, "Function 'pico_vector_iterator_next' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pico_vector_push_back_CallInstance, cmock_line, "Function 'pico_vector_push_back' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pico_vector_pop_back_CallInstance, cmock_line, "Function 'pico_vector_pop_back' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pico_vector_clear_CallInstance, cmock_line, "Function 'pico_vector_clear' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pico_vector_destroy_CallInstance, cmock_line, "Function 'pico_vector_destroy' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pico_vector_allocation_strategy_times2_CallInstance, cmock_line, "Function 'pico_vector_allocation_strategy_times2' called less times than expected.");
}

void Mockpico_vector_Init(void)
{
  Mockpico_vector_Destroy();
}

void Mockpico_vector_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

struct pico_vector_iterator* pico_vector_begin(const struct pico_vector* vector)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pico_vector_begin_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_begin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pico_vector_begin_CallInstance);
  Mock.pico_vector_begin_CallInstance = CMock_Guts_MemNext(Mock.pico_vector_begin_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'pico_vector_begin' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_vector), (void*)(vector), sizeof(struct pico_vector), cmock_line, "Function 'pico_vector_begin' called with unexpected value for argument 'vector'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pico_vector_begin(CMOCK_pico_vector_begin_CALL_INSTANCE* cmock_call_instance, const struct pico_vector* vector)
{
  cmock_call_instance->Expected_vector = (struct pico_vector*)vector;
}

void pico_vector_begin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct pico_vector* vector, struct pico_vector_iterator* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pico_vector_begin_CALL_INSTANCE));
  CMOCK_pico_vector_begin_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_begin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.pico_vector_begin_CallInstance = CMock_Guts_MemChain(Mock.pico_vector_begin_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pico_vector_begin(cmock_call_instance, vector);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

struct pico_vector_iterator* pico_vector_iterator_next(struct pico_vector_iterator* iterator)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pico_vector_iterator_next_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_iterator_next_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pico_vector_iterator_next_CallInstance);
  Mock.pico_vector_iterator_next_CallInstance = CMock_Guts_MemNext(Mock.pico_vector_iterator_next_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'pico_vector_iterator_next' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_iterator), (void*)(iterator), sizeof(struct pico_vector_iterator), cmock_line, "Function 'pico_vector_iterator_next' called with unexpected value for argument 'iterator'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pico_vector_iterator_next(CMOCK_pico_vector_iterator_next_CALL_INSTANCE* cmock_call_instance, struct pico_vector_iterator* iterator)
{
  cmock_call_instance->Expected_iterator = iterator;
}

void pico_vector_iterator_next_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct pico_vector_iterator* iterator, struct pico_vector_iterator* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pico_vector_iterator_next_CALL_INSTANCE));
  CMOCK_pico_vector_iterator_next_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_iterator_next_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.pico_vector_iterator_next_CallInstance = CMock_Guts_MemChain(Mock.pico_vector_iterator_next_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pico_vector_iterator_next(cmock_call_instance, iterator);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int pico_vector_push_back(struct pico_vector* vector, void* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pico_vector_push_back_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_push_back_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pico_vector_push_back_CallInstance);
  Mock.pico_vector_push_back_CallInstance = CMock_Guts_MemNext(Mock.pico_vector_push_back_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'pico_vector_push_back' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_vector), (void*)(vector), sizeof(struct pico_vector), cmock_line, "Function 'pico_vector_push_back' called with unexpected value for argument 'vector'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_data, data, cmock_line, "Function 'pico_vector_push_back' called with unexpected value for argument 'data'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pico_vector_push_back(CMOCK_pico_vector_push_back_CALL_INSTANCE* cmock_call_instance, struct pico_vector* vector, void* data)
{
  cmock_call_instance->Expected_vector = vector;
  cmock_call_instance->Expected_data = data;
}

void pico_vector_push_back_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct pico_vector* vector, void* data, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pico_vector_push_back_CALL_INSTANCE));
  CMOCK_pico_vector_push_back_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_push_back_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.pico_vector_push_back_CallInstance = CMock_Guts_MemChain(Mock.pico_vector_push_back_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pico_vector_push_back(cmock_call_instance, vector, data);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void* pico_vector_pop_back(struct pico_vector* vector)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pico_vector_pop_back_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_pop_back_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pico_vector_pop_back_CallInstance);
  Mock.pico_vector_pop_back_CallInstance = CMock_Guts_MemNext(Mock.pico_vector_pop_back_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'pico_vector_pop_back' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_vector), (void*)(vector), sizeof(struct pico_vector), cmock_line, "Function 'pico_vector_pop_back' called with unexpected value for argument 'vector'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pico_vector_pop_back(CMOCK_pico_vector_pop_back_CALL_INSTANCE* cmock_call_instance, struct pico_vector* vector)
{
  cmock_call_instance->Expected_vector = vector;
}

void pico_vector_pop_back_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct pico_vector* vector, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pico_vector_pop_back_CALL_INSTANCE));
  CMOCK_pico_vector_pop_back_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_pop_back_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.pico_vector_pop_back_CallInstance = CMock_Guts_MemChain(Mock.pico_vector_pop_back_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pico_vector_pop_back(cmock_call_instance, vector);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void pico_vector_clear(struct pico_vector* vector)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pico_vector_clear_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pico_vector_clear_CallInstance);
  Mock.pico_vector_clear_CallInstance = CMock_Guts_MemNext(Mock.pico_vector_clear_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'pico_vector_clear' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_vector), (void*)(vector), sizeof(struct pico_vector), cmock_line, "Function 'pico_vector_clear' called with unexpected value for argument 'vector'.");
  }
}

void CMockExpectParameters_pico_vector_clear(CMOCK_pico_vector_clear_CALL_INSTANCE* cmock_call_instance, struct pico_vector* vector)
{
  cmock_call_instance->Expected_vector = vector;
}

void pico_vector_clear_CMockExpect(UNITY_LINE_TYPE cmock_line, struct pico_vector* vector)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pico_vector_clear_CALL_INSTANCE));
  CMOCK_pico_vector_clear_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.pico_vector_clear_CallInstance = CMock_Guts_MemChain(Mock.pico_vector_clear_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pico_vector_clear(cmock_call_instance, vector);
}

void pico_vector_destroy(struct pico_vector* vector)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pico_vector_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pico_vector_destroy_CallInstance);
  Mock.pico_vector_destroy_CallInstance = CMock_Guts_MemNext(Mock.pico_vector_destroy_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'pico_vector_destroy' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_vector), (void*)(vector), sizeof(struct pico_vector), cmock_line, "Function 'pico_vector_destroy' called with unexpected value for argument 'vector'.");
  }
}

void CMockExpectParameters_pico_vector_destroy(CMOCK_pico_vector_destroy_CALL_INSTANCE* cmock_call_instance, struct pico_vector* vector)
{
  cmock_call_instance->Expected_vector = vector;
}

void pico_vector_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line, struct pico_vector* vector)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pico_vector_destroy_CALL_INSTANCE));
  CMOCK_pico_vector_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.pico_vector_destroy_CallInstance = CMock_Guts_MemChain(Mock.pico_vector_destroy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pico_vector_destroy(cmock_call_instance, vector);
}

void* pico_vector_allocation_strategy_times2(struct pico_vector* vector)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pico_vector_allocation_strategy_times2_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_allocation_strategy_times2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pico_vector_allocation_strategy_times2_CallInstance);
  Mock.pico_vector_allocation_strategy_times2_CallInstance = CMock_Guts_MemNext(Mock.pico_vector_allocation_strategy_times2_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'pico_vector_allocation_strategy_times2' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_vector), (void*)(vector), sizeof(struct pico_vector), cmock_line, "Function 'pico_vector_allocation_strategy_times2' called with unexpected value for argument 'vector'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pico_vector_allocation_strategy_times2(CMOCK_pico_vector_allocation_strategy_times2_CALL_INSTANCE* cmock_call_instance, struct pico_vector* vector)
{
  cmock_call_instance->Expected_vector = vector;
}

void pico_vector_allocation_strategy_times2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct pico_vector* vector, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pico_vector_allocation_strategy_times2_CALL_INSTANCE));
  CMOCK_pico_vector_allocation_strategy_times2_CALL_INSTANCE* cmock_call_instance = (CMOCK_pico_vector_allocation_strategy_times2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.pico_vector_allocation_strategy_times2_CallInstance = CMock_Guts_MemChain(Mock.pico_vector_allocation_strategy_times2_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pico_vector_allocation_strategy_times2(cmock_call_instance, vector);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

